// Generated by LiveScript 1.2.0
(function(){
  var toString$ = {}.toString;
  module.exports = signature;
  function signature(sig, options){
    options.failure || (options.failure = function(req, res, next){
      return next({
        status: 401
      });
    });
    return function(req, res, next){
      if (validate(sig, req)) {
        return next();
      } else {
        return options.failure(req, res, next);
      }
    };
  }
  function validate(cond, o, key){
    var val, $key, i$, len$, $cond;
    val = key ? o[key] : o;
    switch (toString$.call(cond).slice(8, -1)) {
    case 'Object':
      for ($key in cond) {
        if (!validate(cond[$key], val, $key)) {
          return false;
        }
      }
      break;
    case 'Array':
      for (i$ = 0, len$ = cond.length; i$ < len$; ++i$) {
        $cond = cond[i$];
        if (!validate($cond, o, key)) {
          return false;
        }
      }
      break;
    case 'RegExp':
      if (!(val && val.match(cond))) {
        return false;
      }
      break;
    case 'Function':
      if (!cond(val, o, key)) {
        return false;
      }
      break;
    case 'String':
      /* built-in types */
      switch (cond) {
      case 'double':
      case 'float':
        if (!val) {
          return false;
        }
        o[key] = parseFloat(val);
        break;
      case 'int':
      case 'integer':
        if (!val) {
          return false;
        }
        o[key] = parseInt(val);
        break;
      case 'bool':
      case 'boolean':
        o[key] = (val && val !== 'false') || false;
        break;
      case 'string':
        o[key] = o[key].toString();
      }
    }
    return true;
  }
  signature.validate = validate;
  signature.email = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;
}).call(this);
